// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzbroLUOpBD7gDOkZRFyhT7UIdcR-x8XE',
    appId: '1:374801652778:web:f04d15c630b999622d7753',
    messagingSenderId: '374801652778',
    projectId: 'chatappmc-4385c',
    authDomain: 'chatappmc-4385c.firebaseapp.com',
    storageBucket: 'chatappmc-4385c.appspot.com',
    measurementId: 'G-6D1VVYXEHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgopj8wVu4soOUoHjSzC7l9dfQmUKwpqE',
    appId: '1:374801652778:android:b49e4e679d639a252d7753',
    messagingSenderId: '374801652778',
    projectId: 'chatappmc-4385c',
    storageBucket: 'chatappmc-4385c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVG-b2roCoMgevIAThfeDDuQ0MIkvUTk',
    appId: '1:374801652778:ios:109d6ea15efd1fa02d7753',
    messagingSenderId: '374801652778',
    projectId: 'chatappmc-4385c',
    storageBucket: 'chatappmc-4385c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVG-b2roCoMgevIAThfeDDuQ0MIkvUTk',
    appId: '1:374801652778:ios:e6fcf7200d81422d2d7753',
    messagingSenderId: '374801652778',
    projectId: 'chatappmc-4385c',
    storageBucket: 'chatappmc-4385c.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
